name: 풀리퀘스트 생성 및 프로젝트 빌드

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-pull-request:
    permissions: write-all
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: echo "Creating a pull request..."

      # - name: Set up GitHub CLI
      #   run: |
      #     sudo apt-get install gh

      # - name: Create Pull Request
      #   run: |
      #     gh pr create --base develop --head ${{ github.head_ref }} --title "New Pull Request" --body "This is an automated pull request."

  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install Dependencies
        run: |
          npm install    

      - name: Run Build
        run: |
          npm run build
      
      - name: Pull Request Labeling
        uses: actions/labeler@v5